name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of tmdbv3 are you running?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running?
      options:
        - Node.js 20.x
        - Node.js 18.x
        - Node.js 16.x
        - Other (specify in environment)
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: Please provide a minimal code example that reproduces the issue
      render: typescript
      placeholder: |
        import { init } from 'tmdbv3';

        const tmdb = init('your-api-key');
        // Code that reproduces the issue...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide any additional environment details that might be relevant.
        Examples: Operating System, TypeScript version, etc.
      placeholder: |
        OS: macOS 13.0
        TypeScript: 5.3.0
        Other relevant details...
    validations:
      required: false
